### ISSUE TITLE
visually differentiated (or no) search location marker

### ISSUE THREAD

**Issue by outofambit** [binx/hrc-events#1]
Is there a way to make the search location marker (this is what I'm calling the pin that appears at the location you searched) look different from the event markers? Don't want people to think its an event.

I'm tempted to say we don't need a marker for that spot at all, since the map centers around where you searched.

**Comment by binx** [comment]
blessed be, I have kicked out the old geocoder and replaced it with a hand-rolled one. There is no longer a pin dropped on search. (which I agree, totally sucked!)

**Comment by outofambit** [comment]
huzzah!
