### ISSUE TITLE
Improve zipcode support

### ISSUE THREAD

**Issue by dsjoerg** [binx/hrc-events#11]

**Comment by dsjoerg** [comment]
Ah I see.  So actually users _can_ enter a zipcode, but when they do:
- the autocomplete is not zipcode aware so it seems as if zipcode entry isnt going to work
- there text prompt above the entry field doesnt mention zipcode entry is supported
- after hitting enter, the field of view is very zoomed-in

**Comment by binx** [comment]
Thanks for the feedback! To answer your points:
1) I unfortunately don't think this will be possible in the short term (at least using the current autocomplete API). I'm using https://mapzen.com/documentation/search/autocomplete/, which doesn't have zipcode support :( I'm currently handling zip codes manually with a obj lookup... I suppose one thing we could do is if the search string == Number && len==5, we could manually insert a "zip code: XXXXX" option in the drop down that would initiate a zip code lookup. @dsjoerg thoughts?

2) and 3) I can fix easily, I will self-assign this and get those in.

**Comment by dsjoerg** [comment]
I like your idea of manually doing "zip code: XXXXX" for five-digit numbers _instead_ of the nonsense that mapzen shows
