### ISSUE TITLE
Remove H trademark

### ISSUE THREAD

**Issue by dsjoerg** [binx/hrc-events#12]
When I was working on hillarybnb.com the campaign requested that the H trademark be removed.  I'm sure when they look at this project they'll make the same request.

**Comment by dsjoerg** [comment]
Hey @binx and others what do you think of the "h" logo up at hillarybnb.com?  If you like it I'll submit a PR to swap that in for the trademark H.

**Comment by binx** [comment]
This looks great! I was just grasping at straws with the H trademark logo, I'm happy to use whatever logo is better :)
