### ISSUE TITLE
Move our work over to DevProgress/hrc-events?

### ISSUE THREAD

**Issue by dsjoerg** [binx/hrc-events#16]
@binx are you cool with us moving our work over to https://github.com/DevProgress/hrc-events ?

If so, if you grant me sufficient admin privileges I can do it, or if you get repo-creation privileges on DevProgress you can do it.

We moved HillaryBNB over to DevProgress, makes the whole thing seem more official shiny and exciting.

**Comment by binx** [comment]
yes, let's do it!

I'm having a hard time figuring out how to assign admin privileges on a personal repo, but I'm happy to follow whatever steps to do that. Or I can move it to DevProgress if I get added, I believe @decause would need to do that?

**Comment by dsjoerg** [comment]
You can set me as admin like this:
![image](https://cloud.githubusercontent.com/assets/783273/17489212/f9b9ae3e-5d6a-11e6-999d-28220e66bca7.png)

**Comment by binx** [comment]
Yeah unfortunately it's not set up as a team... I am investigating this now

![screen shot 2016-08-08 at 10 22 33 am](https://cloud.githubusercontent.com/assets/589151/17489302/35318888-5d52-11e6-86f7-cb321a8606a3.png)

**Comment by dsjoerg** [comment]
Alright well I vote to deprioritize this for now and when it becomes an issue then Seeyew or someone can grant you repo-creation rights on DevProgress.

**Comment by decause** [comment]
@binx you've been added as an organization member. Lemme know if you need any other privs.

**Comment by wboykinm** [comment]
All clear here! New url: https://devprogress.us/hrc-events/
