### ISSUE TITLE
A stab at visual design

### ISSUE THREAD

**Issue by aaronshekey** [binx/hrc-events#31]
Howdy! Happy to be helping with this project. I've had a gander at #8, and started riffing on some visual presentations of this. Right now, this is made to represent the HRC campaign. Fonts aren't quite right, but these mockups use a close approximation. We can easily run with our own styling. Not sure.
#### Landing

![landing01](https://cloud.githubusercontent.com/assets/1369864/17602799/d6109f2c-5fd3-11e6-8f8b-4cdf315c4840.png)
We can land on the map zoomed out like we have now, prompting the user to search for a location. We could experiment with having it ask for location by default. If they accept, we can search the map automatically.
#### Results

![results01](https://cloud.githubusercontent.com/assets/1369864/17602802/d84cff06-5fd3-11e6-9f16-1453e65395fb.png)
Once the location is found, show the results in a smaller sidebar. I don't think we need to show the search radius. Users can modify the zoom level. I also think we can default to "redo the search when map moved."

Clearing the search field would mimic the behavior we have today.
#### Landing Alternative

![landing02](https://cloud.githubusercontent.com/assets/1369864/17602800/d72e7956-5fd3-11e6-8874-8adc17117bdb.png)

This pulls copy and a call to action from the HRC [/events/](http://hillaryclinton.com/events/) page. This would likely separate the first search with map presentation. Not sure if there's a ton to gain from showing this first page, but it shows how this could be integrated with the [/events/](http://hillaryclinton.com/events/) page.
### Questions
1. Can we use campaign assets?
2. If so, where can we get the fonts?
3. How's everyone feel about this direction?
4. What'd I miss?

**Comment by bradyk** [comment]
Answers: 
1. Not right now. Right now we're doing our own branding. Check the branding slack channel. We're deciding on fonts and colors.
2. We are deciding on a font for DevProgress, but whatever we decide on it'll be open.
3. I love this direction
4. Nothing, you're the best.

**Comment by binx** [comment]
3) 🎉  love it!!!

**Comment by wboykinm** [comment]
@bradyk does the branding restriction mean that the map markers shouldn't incorporate the campaign logo? (A possibly heavy-handed effect that @binx and @aaronshekey are welcome to shout down anyway)

**Comment by outofambit** [comment]
@aaronshekey Looks great to me too! I agree on nixing the search search radius dropdown and limiting the search to the viewport by default.

What were you thinking for the behavior of the 'more' link at the end of the description? Would it expand that element of the list in place, pushing the lower ones down?

**Comment by aaronshekey** [comment]
> What were you thinking for the behavior of the 'more' link at the end of the description? Would it expand that element of the list in place, pushing the lower ones down?

I was thinking we could have it expand inline, for sure. Could be easier to just link that "more" to a permalink for the event. Either way!

**Comment by outofambit** [comment]
Ooo, I like the permalink idea.
