### ISSUE TITLE
Clicking on a marker should scroll to and highlight an entry on the left

### ISSUE THREAD

**Issue by iandees** [binx/hrc-events#39]
Rather than use a popup to show the details of an event, it might make more sense to scroll to and highlight the individual event in the result list on the left when a marker is clicked in the map.

Along the same lines: when an entry is focused in the result list on the left, maybe highlight or change the marker's color on the map?

**Comment by kielni** [comment]
I'll work on this today.

**Comment by wboykinm** [comment]
Zing. Well done, @kielni:

![scroll](https://www.dropbox.com/s/zklfa28i8y7vubm/scroll.gif?dl=1)
