### ISSUE TITLE
Use font awesome map marker instead of symbolicons

### ISSUE THREAD

**Issue by wboykinm** [binx/hrc-events#42]
Adjectives for the current one include "squat", "squashed" and "css error".

[Here's the fa SVG](https://raw.githubusercontent.com/encharm/Font-Awesome-SVG-PNG/master/black/svg/map-marker.svg) - it needs `fill: #5CA6E0` and a `#ffffff` halo.

**Comment by aaronshekey** [comment]
Are you referring to the markers on the map itself?

I wouldn't mind using a filled version of what I've built for [Octicons](https://octicons.github.com/icon/location/). I think it scales well, and we're already using it in the events listing / map popover.

**Comment by wboykinm** [comment]
@aaronshekey That's perfect! Does it have a compatible license?

**Comment by wboykinm** [comment]
![demo](https://www.dropbox.com/s/hhyb0si9qa7xv7i/Screenshot%202016-08-23%2022.20.26.png?dl=1)

**Comment by wboykinm** [comment]
Hoping the licensing is all set, but closing.

**Comment by aaronshekey** [comment]
Yep, Octicons is fully open source with an MIT license.

**Comment by wboykinm** [comment]
Woot! Thanks!
