### ISSUE TITLE
mobile layout

### ISSUE THREAD

**Issue by wboykinm** [binx/hrc-events#43]
to keep it simple, I propose for `@media all and (max-width: 720px) {}` we move the sidebar into a footer that gets 33% of screen height.

@binx @aaronshekey Seem reasonable? Does that open a can of worms for the `#searchbox`?

**Comment by aaronshekey** [comment]
I was thinking about this too. I think that's all we need to do.

Perhaps not a footer though, considering we've got the dropdown for autocomplete. That may push things around in an annoying way on smaller screens. The `#searchbox` layout itself should be completely fluid regardless of the size of its parent, so we're good there.

If you feel like opening a branch / pr for that, I can clean up any rough edges.

**Comment by kielni** [comment]
I don't think there's room for an always open sidebar or footer, at least on a phone. How about a floating search box with a button to slide out the sidebar, like Google Maps?

<IMG SRC="https://cloud.githubusercontent.com/assets/1649528/18030032/dc83b27c-6c5d-11e6-9f14-cc641024c3e4.png" width="300px">

<IMG SRC="https://cloud.githubusercontent.com/assets/1649528/18030036/eeea2108-6c5d-11e6-9315-2e95d046346e.png" width="300px">

**Comment by wboykinm** [comment]
@kielni I have a sense that the drawer UI is pretty well-conditioned in users to contain tools and configuration instead of content, but you're right that it's a good way to clear things off the map. What about (with apologies to tinder) a swipe interface on the bottom of the map, with the same fixed search bar you mentioned?

a la [this mockup](https://dribbble.com/shots/2684582-Map-swipe-through-animation):

![swipe](https://d13yacurqjgara.cloudfront.net/users/17917/screenshots/2684582/map-animated-mockup.gif)

**Comment by wboykinm** [comment]
Basic mobile UI is covered by #52 and #53, now merged. What's left is detailed in #54

**Comment by wboykinm** [comment]
Great work @kielni! 

![mobile](https://www.dropbox.com/s/ckn2xe45a584c3v/Screenshot%202016-08-30%2017.24.18.png?dl=1)
