### ISSUE TITLE
when redo search by area is checked, map markers flickr on load

### ISSUE THREAD

**Issue by mikelmaron** [binx/hrc-events#45]
one idea, implement update of markers [here](https://github.com/DevProgress/hrc-events/blob/master/js/event-map.js#L240-L243), by comparing current markers with new markers, rather than remove and add back

**Comment by kielni** [comment]
I'll take a look at this later tonight/early tomorrow.

**Comment by wboykinm** [comment]
Great work, @kielni - thanks!

**Comment by mikelmaron** [comment]
works great for me, awesome @kielni
