### ISSUE TITLE
incorporate/use Hillary logo/arrow, rather than standard map marker

### ISSUE THREAD

**Issue by mikelmaron** [binx/hrc-events#46]

**Comment by wboykinm** [comment]
Any design-ish folks want to take a whack at this one? I couldn't get the campaign logo to look less-than-noisy on a map marker.

**Comment by flibbertigibbet** [comment]
Tried using a downsized version of the logo itself for an icon, and it is pretty noisy:

![image](https://cloud.githubusercontent.com/assets/960264/18292481/5511d6c4-745b-11e6-9e75-c6372d3422bb.png)

(on `feature/logo-map-icons` branch)

**Comment by wboykinm** [comment]
@flibbertigibbet Yeah, plus it looks almost unrecognizable when shrunken to fit on the existing marker. 

Can you humor me by putting a 1px #ffffff stroke around the logo you used above and trying it out?

**Comment by flibbertigibbet** [comment]
I'm not a designer. I can only manage to put a border around the entire, square image rather than the non-transparent shapes within it.

**Comment by wboykinm** [comment]
No worries. I think we'll leave it at "too noisy".
