### ISSUE TITLE
Swipe through events on mobile

### ISSUE THREAD

**Issue by wboykinm** [binx/hrc-events#54]
**Proposal**: integrate [the swipe.js jquery plugin](http://codepen.io/wboykinm/pen/qaWObK) with the current mobile layout to produce a UI like this (another example is AirBnB mobile):

![swipe](https://camo.githubusercontent.com/0e997a56a605a64129cc2e707c38b221ebd400be/68747470733a2f2f6431337961637572716a676172612e636c6f756466726f6e742e6e65742f75736572732f31373931372f73637265656e73686f74732f323638343538322f6d61702d616e696d617465642d6d6f636b75702e676966)

This might require a subtle refactor of the `#detail` element to contain multitudes - as it stands the content is swapped instead of the "hide most of the card elements" strategy in the codepen above.

**Comment by kielni** [comment]
I'm doing this now.

**Comment by kielni** [comment]
Can you tell me where you found that swipe plugin?  I see //cdnjs.cloudflare.com/ajax/libs/swipe/2.0/swipe.min.js but it'd be helpful if I could read the directions/usage info.

**Comment by wboykinm** [comment]
[This is it](https://github.com/thebird/swipe); kinda limited docs, but seems like a basic pattern.

**Comment by kielni** [comment]
I'm working on this and https://github.com/DevProgress/hrc-events/issues/55 in https://github.com/kielni/hrc-events/tree/swipe-info; should be done in one more day.

**Comment by wboykinm** [comment]
Nailed. it.
