### ISSUE TITLE
Easy dismissal of info card on mobile

### ISSUE THREAD

**Issue by wboykinm** [binx/hrc-events#55]
Currently no clear way to return to fullscreen map after selecting an event. Bear in mind the solution here will have to dovetail with #54.

![mobile](https://www.dropbox.com/s/ckn2xe45a584c3v/Screenshot%202016-08-30%2017.24.18.png?dl=1)

Anyone have any strong preferences about how to do this? `x` button? Drawer slider? Special dance?

**Comment by kielni** [comment]
Right now if you click on the map (not a marker), it will dismiss it, but clearly that's not obvious.  What do you think about a swipe down?

**Comment by wboykinm** [comment]
I'm finding the map click doesn't dismiss the card on android or chrome's mobile emulator:

![dismiss](https://www.dropbox.com/s/patp53laixs6jnb/dismiss.gif?dl=1)

A swipe down action sounds awesome if you've got something handy for it.

**Comment by wboykinm** [comment]
Still needed as of the swipe merge.

**Comment by kielni** [comment]
Tapping on the card should dismiss it.  I tried it on https://devprogress.us/hrc-events with Chrome on Nexus 5 and it worked.

**Comment by wboykinm** [comment]
So it does! Nice!
