### ISSUE TITLE
Page load performance

### ISSUE THREAD

**Issue by kielni** [binx/hrc-events#59]
Things I noticed from loading https://devprogress.us/hrc-events/
- js/zipcode.js is huge (1.0M) but only used if user searches a zip.  Don't block page load waiting for this; load after map is drawn instead.
- Map doesn't draw until after events search returns.  The event search is slow-ish (500ms) and may  do multiple searches if it doesn't find events.  Draw the map as soon a location is available, and add the markers / adjust the zoom after the events come back.
- Ideally we'd concatenate the dependencies to reduce network overhead, but I think the first two issues are more important.

**Comment by wboykinm** [comment]
Item 2 is an awesome find - I had thought that delay was coming down the user geolocation pipe.

**Comment by wboykinm** [comment]
https://github.com/kielni/hrc-events/pull/1/files
