### ISSUE TITLE
Add a throttle on the autocomplete requests

### ISSUE THREAD

**Issue by binx** [binx/hrc-events#6]

**Comment by dsjoerg** [comment]
Is this issue related to the errors in my console saying "Failed to load resource: the server responded with a status of 429 (Too Many Requests)
https://search.mapzen.com/v1/autocomplete?text=537%202nd&api_key=search-Ff4Gs8o Failed to load resource: the server responded with a status of 429 (Too Many Requests)" ?

**Comment by binx** [comment]
^ @dsjoerg yes!

the only change I want to make on your throttle PR is to drop the timeout from 1000ms to 100, the server should be able to handle 100ms just fine :)

**Comment by dsjoerg** [comment]
OK its there
