### ISSUE TITLE
add link to DevProgress in source

### ISSUE THREAD

**Issue by kielni** [binx/hrc-events#61]
can we copy the banner from https://devprogress.us/maps-showcase/site/map.html?
plus console.log message: if you're reading this, come join us at devprogress.us

**Comment by wboykinm** [comment]
I think we'll leave the banner alone for now, but [this is up now](https://github.com/DevProgress/hrc-events/commit/fbcd3955e725f4ecc244d2bc8447783d7b987ef7):

![visitor](https://www.dropbox.com/s/uu2hs0xilqap26j/Screenshot%202016-09-12%2010.07.07.png?dl=1)
