### ISSUE TITLE
search box suggestions appear in wrong place

### ISSUE THREAD

**Issue by outofambit** [binx/hrc-events#7]
At least on Safari, the top of the suggestions list box landing just below the search button

**Comment by binx** [comment]
@outofambit can you post a screenshot? It's looking pretty much what I would expect on my safari...

![screen shot 2016-08-08 at 9 31 55 am](https://cloud.githubusercontent.com/assets/589151/17487731/fcb86316-5d4a-11e6-9aa6-a874a798fdb7.png)

**Comment by outofambit** [comment]
ah i see now, its a reflow issue. if i make my browser too narrow (I have a 13" screen at home) it puts the submit button on the line below and the autocompletes below that.

![screen shot 2016-08-08 at 9 51 51 am](https://cloud.githubusercontent.com/assets/964912/17488439/4e0a6680-5d4e-11e6-95a3-e41c7a0b5332.png)

**Comment by binx** [comment]
aha! yes good catch.

This speaks to the larger issue that the site is not especially responsive at the moment. We might need to add some (grr) Bootstrap-esque layout classes.

Also I have given 0 thought to the mobile version of this.

**Comment by outofambit** [comment]
😄 lets defer this to the conversation in #8
