### ISSUE TITLE
time slider

### ISSUE THREAD

**Issue by outofambit** [binx/hrc-events#9]
i think it would be useful to be able to specify a time window for your geographic search. Perhaps via slider and just expressed in how many hours/days/weeks in the future the search includes.

**Comment by iandees** [comment]
I agree! A really simple addition would be to add a dropdown beneath the search bar that let's people select events "Happening today", "Happening this week", or "Happening this weekend" or something.

**Comment by wboykinm** [comment]
Finished with #48
